import os

DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')
DATABASE_HOST = '127.0.0.1'
DATABASE_PORT = '5432'

STATIC_SALT = os.getenv('STATIC_SALT')
